name: rag_ollama
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - annotated-types=0.7.0
  - anyio=4.12.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asgiref=3.11.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - async-timeout=4.0.3
  - attrs=25.4.0
  - babel=2.17.0
  - backoff=2.2.1
  - backports.zstd=1.2.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.3
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - chromadb=1.2.1
  - click=8.3.1
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.3
  - cpython=3.12.12
  - cryptography=46.0.3
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - dataclasses-json=0.6.7
  - debugpy=1.8.18
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.3.1
  - distro=1.9.0
  - dnspython=2.8.0
  - durationpy=0.10
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - fastapi=0.115.9
  - fastapi-cli=0.0.16
  - filelock=3.20.0
  - fqdn=1.5.1
  - frozenlist=1.7.0
  - fsspec=2025.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.43.0
  - googleapis-common-protos=1.72.0
  - greenlet=3.3.0
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - httpx-sse=0.4.3
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - langchain=1.1.3
  - langchain-chroma=1.0.0
  - langchain-community=0.3.31
  - langchain-core=1.2.0
  - langchain-ollama=1.0.1
  - langchain-text-splitters=0.3.11
  - langgraph=1.0.5
  - langgraph-checkpoint=3.0.1
  - langgraph-prebuilt=1.0.5
  - langgraph-sdk=0.3.0
  - langsmith=0.4.59
  - lark=1.3.1
  - ld_impl_linux-64=2.45
  - libabseil=20250512.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.4.1.4
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusparse=12.5.10.65
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libprotobuf=6.31.1
  - libpulsar=3.8.0
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - marshmallow=3.26.1
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mistune=3.1.4
  - mmh3=5.2.0
  - monotonic=1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - mypy_extensions=1.1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - oauthlib=3.3.1
  - ollama-python=0.6.1
  - openssl=3.6.0
  - opentelemetry-api=1.39.1
  - opentelemetry-exporter-otlp-proto-common=1.39.1
  - opentelemetry-exporter-otlp-proto-grpc=1.39.1
  - opentelemetry-instrumentation=0.60b1
  - opentelemetry-instrumentation-asgi=0.60b1
  - opentelemetry-instrumentation-fastapi=0.60b1
  - opentelemetry-proto=1.39.1
  - opentelemetry-sdk=1.39.1
  - opentelemetry-semantic-conventions=0.60b1
  - opentelemetry-util-http=0.60b1
  - orjson=3.11.5
  - ormsgpack=1.12.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - posthog=5.4.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=6.31.1
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pulsar-client=3.8.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybase64=1.4.3
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyopenssl=25.3.0
  - pypika=0.48.9
  - pyproject_hooks=1.2.0
  - pysocks=1.7.1
  - python=3.12.12
  - python-build=1.3.0
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-fastjsonschema=2.21.2
  - python-flatbuffers=25.9.23
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-kubernetes=33.1.0
  - python-multipart=0.0.20
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.12
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rich-toolkit=0.17.0
  - rpds-py=0.30.0
  - rsa=4.9.1
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlalchemy=2.0.45
  - stack_data=0.6.3
  - starlette=0.45.3
  - sympy=1.14.0
  - tenacity=9.1.2
  - terminado=0.18.1
  - tinycss2=1.5.1
  - tk=8.6.13
  - tokenizers=0.22.2
  - tomli=2.3.0
  - tornado=6.5.3
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - uri-template=1.3.0
  - urllib3=2.6.2
  - uuid-utils=0.12.0
  - uvicorn=0.38.0
  - uvicorn-standard=0.38.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.3
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiofiles==25.1.0
      - antlr4-python3-runtime==4.9.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - effdet==0.4.1
      - emoji==2.15.0
      - filetype==1.2.0
      - fonttools==4.61.1
      - google-api-core==2.28.1
      - google-cloud-vision==3.11.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - html5lib==1.1
      - huggingface-hub==0.36.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - langdetect==1.0.9
      - lxml==6.0.2
      - matplotlib==3.10.8
      - ml-dtypes==0.5.4
      - networkx==3.6.1
      - nltk==3.9.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - olefile==0.47
      - omegaconf==2.3.0
      - onnx==1.20.0
      - onnxruntime==1.23.2
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pdf2image==1.17.0
      - pdfminer-six==20251107
      - pi-heif==1.1.1
      - pikepdf==10.0.2
      - pillow==12.0.0
      - proto-plus==1.26.1
      - pycocotools==2.0.10
      - pyparsing==3.2.5
      - pypdf==6.4.2
      - pypdfium2==5.2.0
      - python-iso639==2025.11.16
      - python-magic==0.4.27
      - python-oxmsg==0.0.2
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - safetensors==0.7.0
      - scipy==1.16.3
      - timm==1.0.22
      - torch==2.9.1
      - torchvision==0.24.1
      - transformers==4.57.3
      - triton==3.5.1
      - unstructured==0.18.21
      - unstructured-client==0.42.4
      - unstructured-inference==1.1.2
      - unstructured-pytesseract==0.3.15
